services:
  kafka:
    image: apache/kafka
    ports:
      - "9092:9092"

    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_INITIAL_BROKER_REGISTRATION_TIMEOUT_MS=30000

  producer:
    build:
      context: .
      dockerfile: cmd/producer/Dockerfile
    depends_on:
      - kafka
    restart: on-failure

  web-server:
    build:
      context: .
      dockerfile: cmd/web-server/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    restart: on-failure

  vue-client:
    build:
      context: ./client
    ports:
      - "8081:80"
